"""Tests for the HTTP service."""
from __future__ import annotations

import json
import threading
import time
import urllib.error
import urllib.request
from http.server import ThreadingHTTPServer

import pytest

from gan_matchmaking.persistence import InMemoryPipelineStore
from gan_matchmaking.service import build_app
from gan_matchmaking.service.app import _Handler


@pytest.fixture
def server():
    app = build_app(store=InMemoryPipelineStore())

    class Bound(_Handler):
        pass
    Bound.app = app

    httpd = ThreadingHTTPServer(("127.0.0.1", 0), Bound)
    host, port = httpd.server_address
    t = threading.Thread(target=httpd.serve_forever, daemon=True)
    t.start()
    try:
        yield f"http://{host}:{port}", app
    finally:
        httpd.shutdown()
        httpd.server_close()


def _get(url: str):
    try:
        with urllib.request.urlopen(url, timeout=5.0) as resp:
            return resp.status, resp.read().decode("utf-8"), dict(resp.headers)
    except urllib.error.HTTPError as e:
        return e.code, e.read().decode("utf-8"), dict(e.headers or {})


def _post(url: str, payload: dict, extra_headers: dict | None = None):
    data = json.dumps(payload).encode("utf-8")
    req = urllib.request.Request(url, data=data, method="POST",
                                 headers={"Content-Type": "application/json",
                                          **(extra_headers or {})})
    try:
        with urllib.request.urlopen(req, timeout=5.0) as resp:
            return resp.status, json.loads(resp.read().decode("utf-8")), dict(resp.headers)
    except urllib.error.HTTPError as e:
        body = e.read().decode("utf-8")
        try:
            parsed = json.loads(body)
        except json.JSONDecodeError:
            parsed = body
        return e.code, parsed, dict(e.headers or {})


def test_healthz(server):
    url, _ = server
    status, body, _ = _get(f"{url}/healthz")
    assert status == 200
    assert json.loads(body)["status"] == "ok"


def test_readyz_allows_when_breaker_closed(server):
    url, _ = server
    status, body, _ = _get(f"{url}/readyz")
    assert status == 200
    assert json.loads(body)["status"] == "ready"


def test_metrics_endpoint_returns_text(server):
    url, _ = server
    status, body, headers = _get(f"{url}/metrics")
    assert status == 200
    assert headers["Content-Type"].startswith("text/plain")


def test_observe_and_get_service(server):
    url, app = server

    status, body, _ = _post(f"{url}/v1/observe", {
        "service_id": "svc-a", "success": True,
        "duration_seconds": 5.0, "correlation_id": "obs-1"
    })
    assert status == 422  # unknown service — observe_release raises DataError.
    # Seed a service via decide first.
    payload = {
        "service": {"id": "svc-a", "mu": 0.99, "sigma": 0.02},
        "candidates": [{"id": "canary", "strategy": "canary",
                        "canary_fraction": 0.05,
                        "rollback_budget_seconds": 180,
                        "expected_success": 0.99}],
        "correlation_id": "decide-1"
    }
    status, body, headers = _post(f"{url}/v1/decide", payload)
    assert status == 200, body
    assert body["correlation_id"] == "decide-1"
    assert headers["X-Correlation-Id"] == "decide-1"

    # Now observe works.
    status, body, _ = _post(f"{url}/v1/observe", {
        "service_id": "svc-a", "success": True,
        "duration_seconds": 5.0,
        "dependencies": ["dep-a"],
    })
    assert status == 200
    assert app.pipeline.store is not None
    assert app.pipeline.store.synergy.stats("svc-a", "dep-a") == (1, 1)

    status, body, _ = _get(f"{url}/v1/services/svc-a")
    assert status == 200
    payload = json.loads(body)
    assert payload["id"] == "svc-a"
    assert payload["total_releases"] == 1


def test_unknown_endpoint_404(server):
    url, _ = server
    status, _, _ = _get(f"{url}/does-not-exist")
    assert status == 404


def test_malformed_json_gives_400(server):
    url, _ = server
    # Send junk payload.
    req = urllib.request.Request(
        f"{url}/v1/decide", data=b"not-json",
        method="POST", headers={"Content-Type": "application/json"}
    )
    try:
        urllib.request.urlopen(req, timeout=5.0)
        assert False, "should have raised"
    except urllib.error.HTTPError as e:
        assert e.code == 400
        body = json.loads(e.read().decode("utf-8"))
        assert body["error"]["code"] == "gan.http.bad_request"


def test_correlation_id_autogenerated_when_missing(server):
    url, _ = server
    status, _, headers = _get(f"{url}/healthz")
    assert status == 200
    assert headers.get("X-Correlation-Id")
